// Generated by gen.bash.
// DO NOT EDIT THIS FILE DIRECTLY!

package redis

// Cmd is a type for Redis command names.
type Cmd string

const (
	cmdAppend           Cmd = "APPEND"
	cmdAsking           Cmd = "ASKING"
	cmdAuth             Cmd = "AUTH"
	cmdBgrewriteaof     Cmd = "BGREWRITEAOF"
	cmdBgsave           Cmd = "BGSAVE"
	cmdBitcount         Cmd = "BITCOUNT"
	cmdBitop            Cmd = "BITOP"
	cmdBlpop            Cmd = "BLPOP"
	cmdBrpop            Cmd = "BRPOP"
	cmdBrpoplpush       Cmd = "BRPOPLPUSH"
	cmdClient           Cmd = "CLIENT"
	cmdCluster          Cmd = "CLUSTER"
	cmdConfig           Cmd = "CONFIG"
	cmdDbsize           Cmd = "DBSIZE"
	cmdDebug            Cmd = "DEBUG"
	cmdDecr             Cmd = "DECR"
	cmdDecrby           Cmd = "DECRBY"
	cmdDel              Cmd = "DEL"
	cmdDiscard          Cmd = "DISCARD"
	cmdDump             Cmd = "DUMP"
	cmdEcho             Cmd = "ECHO"
	cmdEval             Cmd = "EVAL"
	cmdExec             Cmd = "EXEC"
	cmdExists           Cmd = "EXISTS"
	cmdExpire           Cmd = "EXPIRE"
	cmdExpireat         Cmd = "EXPIREAT"
	cmdFlushall         Cmd = "FLUSHALL"
	cmdFlushdb          Cmd = "FLUSHDB"
	cmdGet              Cmd = "GET"
	cmdGetbit           Cmd = "GETBIT"
	cmdGetrange         Cmd = "GETRANGE"
	cmdGetset           Cmd = "GETSET"
	cmdHdel             Cmd = "HDEL"
	cmdHexists          Cmd = "HEXISTS"
	cmdHget             Cmd = "HGET"
	cmdHgetall          Cmd = "HGETALL"
	cmdHincrby          Cmd = "HINCRBY"
	cmdHincrbyfloat     Cmd = "HINCRBYFLOAT"
	cmdHkeys            Cmd = "HKEYS"
	cmdHlen             Cmd = "HLEN"
	cmdHmget            Cmd = "HMGET"
	cmdHmset            Cmd = "HMSET"
	cmdHset             Cmd = "HSET"
	cmdHsetnx           Cmd = "HSETNX"
	cmdHvals            Cmd = "HVALS"
	cmdIncr             Cmd = "INCR"
	cmdIncrby           Cmd = "INCRBY"
	cmdIncrbyfloat      Cmd = "INCRBYFLOAT"
	cmdInfo             Cmd = "INFO"
	cmdKeys             Cmd = "KEYS"
	cmdLastsave         Cmd = "LASTSAVE"
	cmdLindex           Cmd = "LINDEX"
	cmdLinsert          Cmd = "LINSERT"
	cmdLlen             Cmd = "LLEN"
	cmdLpop             Cmd = "LPOP"
	cmdLpush            Cmd = "LPUSH"
	cmdLpushx           Cmd = "LPUSHX"
	cmdLrange           Cmd = "LRANGE"
	cmdLrem             Cmd = "LREM"
	cmdLset             Cmd = "LSET"
	cmdLtrim            Cmd = "LTRIM"
	cmdMget             Cmd = "MGET"
	cmdMigrate          Cmd = "MIGRATE"
	cmdMonitor          Cmd = "MONITOR"
	cmdMove             Cmd = "MOVE"
	cmdMset             Cmd = "MSET"
	cmdMsetnx           Cmd = "MSETNX"
	cmdMulti            Cmd = "MULTI"
	cmdObject           Cmd = "OBJECT"
	cmdPersist          Cmd = "PERSIST"
	cmdPexpire          Cmd = "PEXPIRE"
	cmdPexpireat        Cmd = "PEXPIREAT"
	cmdPing             Cmd = "PING"
	cmdPsetex           Cmd = "PSETEX"
	cmdPttl             Cmd = "PTTL"
	cmdPublish          Cmd = "PUBLISH"
	cmdRandomkey        Cmd = "RANDOMKEY"
	cmdRename           Cmd = "RENAME"
	cmdRenamenx         Cmd = "RENAMENX"
	cmdReplconf         Cmd = "REPLCONF"
	cmdRestore          Cmd = "RESTORE"
	cmdRpop             Cmd = "RPOP"
	cmdRpoplpush        Cmd = "RPOPLPUSH"
	cmdRpush            Cmd = "RPUSH"
	cmdRpushx           Cmd = "RPUSHX"
	cmdSadd             Cmd = "SADD"
	cmdSave             Cmd = "SAVE"
	cmdScard            Cmd = "SCARD"
	cmdScript           Cmd = "SCRIPT"
	cmdSdiff            Cmd = "SDIFF"
	cmdSdiffstore       Cmd = "SDIFFSTORE"
	cmdSelect           Cmd = "SELECT"
	cmdSet              Cmd = "SET"
	cmdSetbit           Cmd = "SETBIT"
	cmdSetex            Cmd = "SETEX"
	cmdSetnx            Cmd = "SETNX"
	cmdSetrange         Cmd = "SETRANGE"
	cmdShutdown         Cmd = "SHUTDOWN"
	cmdSinter           Cmd = "SINTER"
	cmdSinterstore      Cmd = "SINTERSTORE"
	cmdSismember        Cmd = "SISMEMBER"
	cmdSlaveof          Cmd = "SLAVEOF"
	cmdSmembers         Cmd = "SMEMBERS"
	cmdSmove            Cmd = "SMOVE"
	cmdSort             Cmd = "SORT"
	cmdSpop             Cmd = "SPOP"
	cmdSrandmember      Cmd = "SRANDMEMBER"
	cmdSrem             Cmd = "SREM"
	cmdStrlen           Cmd = "STRLEN"
	cmdSunion           Cmd = "SUNION"
	cmdSunionstore      Cmd = "SUNIONSTORE"
	cmdSync             Cmd = "SYNC"
	cmdTime             Cmd = "TIME"
	cmdTtl              Cmd = "TTL"
	cmdType             Cmd = "TYPE"
	cmdUnwatch          Cmd = "UNWATCH"
	cmdWatch            Cmd = "WATCH"
	cmdZadd             Cmd = "ZADD"
	cmdZcard            Cmd = "ZCARD"
	cmdZcount           Cmd = "ZCOUNT"
	cmdZincrby          Cmd = "ZINCRBY"
	cmdZinterstore      Cmd = "ZINTERSTORE"
	cmdZrange           Cmd = "ZRANGE"
	cmdZrangebyscore    Cmd = "ZRANGEBYSCORE"
	cmdZrank            Cmd = "ZRANK"
	cmdZrem             Cmd = "ZREM"
	cmdZremrangebyrank  Cmd = "ZREMRANGEBYRANK"
	cmdZremrangebyscore Cmd = "ZREMRANGEBYSCORE"
	cmdZrevrange        Cmd = "ZREVRANGE"
	cmdZrevrangebyscore Cmd = "ZREVRANGEBYSCORE"
	cmdZrevrank         Cmd = "ZREVRANK"
	cmdZscore           Cmd = "ZSCORE"
	cmdZunionstore      Cmd = "ZUNIONSTORE"
)

// Append calls Redis APPEND command. 
func (c *Conn) Append(args ...interface{}) *Reply {
	return c.call(cmdAppend, args...)
}

// Asking calls Redis ASKING command. 
func (c *Conn) Asking(args ...interface{}) *Reply {
	return c.call(cmdAsking, args...)
}

// Auth calls Redis AUTH command. 
func (c *Conn) Auth(args ...interface{}) *Reply {
	return c.call(cmdAuth, args...)
}

// Bgrewriteaof calls Redis BGREWRITEAOF command. 
func (c *Conn) Bgrewriteaof(args ...interface{}) *Reply {
	return c.call(cmdBgrewriteaof, args...)
}

// Bgsave calls Redis BGSAVE command. 
func (c *Conn) Bgsave(args ...interface{}) *Reply {
	return c.call(cmdBgsave, args...)
}

// Bitcount calls Redis BITCOUNT command. 
func (c *Conn) Bitcount(args ...interface{}) *Reply {
	return c.call(cmdBitcount, args...)
}

// Bitop calls Redis BITOP command. 
func (c *Conn) Bitop(args ...interface{}) *Reply {
	return c.call(cmdBitop, args...)
}

// Blpop calls Redis BLPOP command. 
func (c *Conn) Blpop(args ...interface{}) *Reply {
	return c.call(cmdBlpop, args...)
}

// Brpop calls Redis BRPOP command. 
func (c *Conn) Brpop(args ...interface{}) *Reply {
	return c.call(cmdBrpop, args...)
}

// Brpoplpush calls Redis BRPOPLPUSH command. 
func (c *Conn) Brpoplpush(args ...interface{}) *Reply {
	return c.call(cmdBrpoplpush, args...)
}

// Client calls Redis CLIENT command. 
func (c *Conn) Client(args ...interface{}) *Reply {
	return c.call(cmdClient, args...)
}

// Cluster calls Redis CLUSTER command. 
func (c *Conn) Cluster(args ...interface{}) *Reply {
	return c.call(cmdCluster, args...)
}

// Config calls Redis CONFIG command. 
func (c *Conn) Config(args ...interface{}) *Reply {
	return c.call(cmdConfig, args...)
}

// Dbsize calls Redis DBSIZE command. 
func (c *Conn) Dbsize(args ...interface{}) *Reply {
	return c.call(cmdDbsize, args...)
}

// Debug calls Redis DEBUG command. 
func (c *Conn) Debug(args ...interface{}) *Reply {
	return c.call(cmdDebug, args...)
}

// Decr calls Redis DECR command. 
func (c *Conn) Decr(args ...interface{}) *Reply {
	return c.call(cmdDecr, args...)
}

// Decrby calls Redis DECRBY command. 
func (c *Conn) Decrby(args ...interface{}) *Reply {
	return c.call(cmdDecrby, args...)
}

// Del calls Redis DEL command. 
func (c *Conn) Del(args ...interface{}) *Reply {
	return c.call(cmdDel, args...)
}

// Discard calls Redis DISCARD command. 
func (c *Conn) Discard(args ...interface{}) *Reply {
	return c.call(cmdDiscard, args...)
}

// Dump calls Redis DUMP command. 
func (c *Conn) Dump(args ...interface{}) *Reply {
	return c.call(cmdDump, args...)
}

// Echo calls Redis ECHO command. 
func (c *Conn) Echo(args ...interface{}) *Reply {
	return c.call(cmdEcho, args...)
}

// Eval calls Redis EVAL command. 
func (c *Conn) Eval(args ...interface{}) *Reply {
	return c.call(cmdEval, args...)
}

// Exec calls Redis EXEC command. 
func (c *Conn) Exec(args ...interface{}) *Reply {
	return c.call(cmdExec, args...)
}

// Exists calls Redis EXISTS command. 
func (c *Conn) Exists(args ...interface{}) *Reply {
	return c.call(cmdExists, args...)
}

// Expire calls Redis EXPIRE command. 
func (c *Conn) Expire(args ...interface{}) *Reply {
	return c.call(cmdExpire, args...)
}

// Expireat calls Redis EXPIREAT command. 
func (c *Conn) Expireat(args ...interface{}) *Reply {
	return c.call(cmdExpireat, args...)
}

// Flushall calls Redis FLUSHALL command. 
func (c *Conn) Flushall(args ...interface{}) *Reply {
	return c.call(cmdFlushall, args...)
}

// Flushdb calls Redis FLUSHDB command. 
func (c *Conn) Flushdb(args ...interface{}) *Reply {
	return c.call(cmdFlushdb, args...)
}

// Get calls Redis GET command. 
func (c *Conn) Get(args ...interface{}) *Reply {
	return c.call(cmdGet, args...)
}

// Getbit calls Redis GETBIT command. 
func (c *Conn) Getbit(args ...interface{}) *Reply {
	return c.call(cmdGetbit, args...)
}

// Getrange calls Redis GETRANGE command. 
func (c *Conn) Getrange(args ...interface{}) *Reply {
	return c.call(cmdGetrange, args...)
}

// Getset calls Redis GETSET command. 
func (c *Conn) Getset(args ...interface{}) *Reply {
	return c.call(cmdGetset, args...)
}

// Hdel calls Redis HDEL command. 
func (c *Conn) Hdel(args ...interface{}) *Reply {
	return c.call(cmdHdel, args...)
}

// Hexists calls Redis HEXISTS command. 
func (c *Conn) Hexists(args ...interface{}) *Reply {
	return c.call(cmdHexists, args...)
}

// Hget calls Redis HGET command. 
func (c *Conn) Hget(args ...interface{}) *Reply {
	return c.call(cmdHget, args...)
}

// Hgetall calls Redis HGETALL command. 
func (c *Conn) Hgetall(args ...interface{}) *Reply {
	return c.call(cmdHgetall, args...)
}

// Hincrby calls Redis HINCRBY command. 
func (c *Conn) Hincrby(args ...interface{}) *Reply {
	return c.call(cmdHincrby, args...)
}

// Hincrbyfloat calls Redis HINCRBYFLOAT command. 
func (c *Conn) Hincrbyfloat(args ...interface{}) *Reply {
	return c.call(cmdHincrbyfloat, args...)
}

// Hkeys calls Redis HKEYS command. 
func (c *Conn) Hkeys(args ...interface{}) *Reply {
	return c.call(cmdHkeys, args...)
}

// Hlen calls Redis HLEN command. 
func (c *Conn) Hlen(args ...interface{}) *Reply {
	return c.call(cmdHlen, args...)
}

// Hmget calls Redis HMGET command. 
func (c *Conn) Hmget(args ...interface{}) *Reply {
	return c.call(cmdHmget, args...)
}

// Hmset calls Redis HMSET command. 
func (c *Conn) Hmset(args ...interface{}) *Reply {
	return c.call(cmdHmset, args...)
}

// Hset calls Redis HSET command. 
func (c *Conn) Hset(args ...interface{}) *Reply {
	return c.call(cmdHset, args...)
}

// Hsetnx calls Redis HSETNX command. 
func (c *Conn) Hsetnx(args ...interface{}) *Reply {
	return c.call(cmdHsetnx, args...)
}

// Hvals calls Redis HVALS command. 
func (c *Conn) Hvals(args ...interface{}) *Reply {
	return c.call(cmdHvals, args...)
}

// Incr calls Redis INCR command. 
func (c *Conn) Incr(args ...interface{}) *Reply {
	return c.call(cmdIncr, args...)
}

// Incrby calls Redis INCRBY command. 
func (c *Conn) Incrby(args ...interface{}) *Reply {
	return c.call(cmdIncrby, args...)
}

// Incrbyfloat calls Redis INCRBYFLOAT command. 
func (c *Conn) Incrbyfloat(args ...interface{}) *Reply {
	return c.call(cmdIncrbyfloat, args...)
}

// Info calls Redis INFO command. 
func (c *Conn) Info(args ...interface{}) *Reply {
	return c.call(cmdInfo, args...)
}

// Keys calls Redis KEYS command. 
func (c *Conn) Keys(args ...interface{}) *Reply {
	return c.call(cmdKeys, args...)
}

// Lastsave calls Redis LASTSAVE command. 
func (c *Conn) Lastsave(args ...interface{}) *Reply {
	return c.call(cmdLastsave, args...)
}

// Lindex calls Redis LINDEX command. 
func (c *Conn) Lindex(args ...interface{}) *Reply {
	return c.call(cmdLindex, args...)
}

// Linsert calls Redis LINSERT command. 
func (c *Conn) Linsert(args ...interface{}) *Reply {
	return c.call(cmdLinsert, args...)
}

// Llen calls Redis LLEN command. 
func (c *Conn) Llen(args ...interface{}) *Reply {
	return c.call(cmdLlen, args...)
}

// Lpop calls Redis LPOP command. 
func (c *Conn) Lpop(args ...interface{}) *Reply {
	return c.call(cmdLpop, args...)
}

// Lpush calls Redis LPUSH command. 
func (c *Conn) Lpush(args ...interface{}) *Reply {
	return c.call(cmdLpush, args...)
}

// Lpushx calls Redis LPUSHX command. 
func (c *Conn) Lpushx(args ...interface{}) *Reply {
	return c.call(cmdLpushx, args...)
}

// Lrange calls Redis LRANGE command. 
func (c *Conn) Lrange(args ...interface{}) *Reply {
	return c.call(cmdLrange, args...)
}

// Lrem calls Redis LREM command. 
func (c *Conn) Lrem(args ...interface{}) *Reply {
	return c.call(cmdLrem, args...)
}

// Lset calls Redis LSET command. 
func (c *Conn) Lset(args ...interface{}) *Reply {
	return c.call(cmdLset, args...)
}

// Ltrim calls Redis LTRIM command. 
func (c *Conn) Ltrim(args ...interface{}) *Reply {
	return c.call(cmdLtrim, args...)
}

// Mget calls Redis MGET command. 
func (c *Conn) Mget(args ...interface{}) *Reply {
	return c.call(cmdMget, args...)
}

// Migrate calls Redis MIGRATE command. 
func (c *Conn) Migrate(args ...interface{}) *Reply {
	return c.call(cmdMigrate, args...)
}

// Monitor calls Redis MONITOR command. 
func (c *Conn) Monitor(args ...interface{}) *Reply {
	return c.call(cmdMonitor, args...)
}

// Move calls Redis MOVE command. 
func (c *Conn) Move(args ...interface{}) *Reply {
	return c.call(cmdMove, args...)
}

// Mset calls Redis MSET command. 
func (c *Conn) Mset(args ...interface{}) *Reply {
	return c.call(cmdMset, args...)
}

// Msetnx calls Redis MSETNX command. 
func (c *Conn) Msetnx(args ...interface{}) *Reply {
	return c.call(cmdMsetnx, args...)
}

// Multi calls Redis MULTI command. 
func (c *Conn) Multi(args ...interface{}) *Reply {
	return c.call(cmdMulti, args...)
}

// Object calls Redis OBJECT command. 
func (c *Conn) Object(args ...interface{}) *Reply {
	return c.call(cmdObject, args...)
}

// Persist calls Redis PERSIST command. 
func (c *Conn) Persist(args ...interface{}) *Reply {
	return c.call(cmdPersist, args...)
}

// Pexpire calls Redis PEXPIRE command. 
func (c *Conn) Pexpire(args ...interface{}) *Reply {
	return c.call(cmdPexpire, args...)
}

// Pexpireat calls Redis PEXPIREAT command. 
func (c *Conn) Pexpireat(args ...interface{}) *Reply {
	return c.call(cmdPexpireat, args...)
}

// Ping calls Redis PING command. 
func (c *Conn) Ping(args ...interface{}) *Reply {
	return c.call(cmdPing, args...)
}

// Psetex calls Redis PSETEX command. 
func (c *Conn) Psetex(args ...interface{}) *Reply {
	return c.call(cmdPsetex, args...)
}

// Pttl calls Redis PTTL command. 
func (c *Conn) Pttl(args ...interface{}) *Reply {
	return c.call(cmdPttl, args...)
}

// Publish calls Redis PUBLISH command. 
func (c *Conn) Publish(args ...interface{}) *Reply {
	return c.call(cmdPublish, args...)
}

// Randomkey calls Redis RANDOMKEY command. 
func (c *Conn) Randomkey(args ...interface{}) *Reply {
	return c.call(cmdRandomkey, args...)
}

// Rename calls Redis RENAME command. 
func (c *Conn) Rename(args ...interface{}) *Reply {
	return c.call(cmdRename, args...)
}

// Renamenx calls Redis RENAMENX command. 
func (c *Conn) Renamenx(args ...interface{}) *Reply {
	return c.call(cmdRenamenx, args...)
}

// Replconf calls Redis REPLCONF command. 
func (c *Conn) Replconf(args ...interface{}) *Reply {
	return c.call(cmdReplconf, args...)
}

// Restore calls Redis RESTORE command. 
func (c *Conn) Restore(args ...interface{}) *Reply {
	return c.call(cmdRestore, args...)
}

// Rpop calls Redis RPOP command. 
func (c *Conn) Rpop(args ...interface{}) *Reply {
	return c.call(cmdRpop, args...)
}

// Rpoplpush calls Redis RPOPLPUSH command. 
func (c *Conn) Rpoplpush(args ...interface{}) *Reply {
	return c.call(cmdRpoplpush, args...)
}

// Rpush calls Redis RPUSH command. 
func (c *Conn) Rpush(args ...interface{}) *Reply {
	return c.call(cmdRpush, args...)
}

// Rpushx calls Redis RPUSHX command. 
func (c *Conn) Rpushx(args ...interface{}) *Reply {
	return c.call(cmdRpushx, args...)
}

// Sadd calls Redis SADD command. 
func (c *Conn) Sadd(args ...interface{}) *Reply {
	return c.call(cmdSadd, args...)
}

// Save calls Redis SAVE command. 
func (c *Conn) Save(args ...interface{}) *Reply {
	return c.call(cmdSave, args...)
}

// Scard calls Redis SCARD command. 
func (c *Conn) Scard(args ...interface{}) *Reply {
	return c.call(cmdScard, args...)
}

// Script calls Redis SCRIPT command. 
func (c *Conn) Script(args ...interface{}) *Reply {
	return c.call(cmdScript, args...)
}

// Sdiff calls Redis SDIFF command. 
func (c *Conn) Sdiff(args ...interface{}) *Reply {
	return c.call(cmdSdiff, args...)
}

// Sdiffstore calls Redis SDIFFSTORE command. 
func (c *Conn) Sdiffstore(args ...interface{}) *Reply {
	return c.call(cmdSdiffstore, args...)
}

// Select calls Redis SELECT command. 
func (c *Conn) Select(args ...interface{}) *Reply {
	return c.call(cmdSelect, args...)
}

// Set calls Redis SET command. 
func (c *Conn) Set(args ...interface{}) *Reply {
	return c.call(cmdSet, args...)
}

// Setbit calls Redis SETBIT command. 
func (c *Conn) Setbit(args ...interface{}) *Reply {
	return c.call(cmdSetbit, args...)
}

// Setex calls Redis SETEX command. 
func (c *Conn) Setex(args ...interface{}) *Reply {
	return c.call(cmdSetex, args...)
}

// Setnx calls Redis SETNX command. 
func (c *Conn) Setnx(args ...interface{}) *Reply {
	return c.call(cmdSetnx, args...)
}

// Setrange calls Redis SETRANGE command. 
func (c *Conn) Setrange(args ...interface{}) *Reply {
	return c.call(cmdSetrange, args...)
}

// Shutdown calls Redis SHUTDOWN command. 
func (c *Conn) Shutdown(args ...interface{}) *Reply {
	return c.call(cmdShutdown, args...)
}

// Sinter calls Redis SINTER command. 
func (c *Conn) Sinter(args ...interface{}) *Reply {
	return c.call(cmdSinter, args...)
}

// Sinterstore calls Redis SINTERSTORE command. 
func (c *Conn) Sinterstore(args ...interface{}) *Reply {
	return c.call(cmdSinterstore, args...)
}

// Sismember calls Redis SISMEMBER command. 
func (c *Conn) Sismember(args ...interface{}) *Reply {
	return c.call(cmdSismember, args...)
}

// Slaveof calls Redis SLAVEOF command. 
func (c *Conn) Slaveof(args ...interface{}) *Reply {
	return c.call(cmdSlaveof, args...)
}

// Smembers calls Redis SMEMBERS command. 
func (c *Conn) Smembers(args ...interface{}) *Reply {
	return c.call(cmdSmembers, args...)
}

// Smove calls Redis SMOVE command. 
func (c *Conn) Smove(args ...interface{}) *Reply {
	return c.call(cmdSmove, args...)
}

// Sort calls Redis SORT command. 
func (c *Conn) Sort(args ...interface{}) *Reply {
	return c.call(cmdSort, args...)
}

// Spop calls Redis SPOP command. 
func (c *Conn) Spop(args ...interface{}) *Reply {
	return c.call(cmdSpop, args...)
}

// Srandmember calls Redis SRANDMEMBER command. 
func (c *Conn) Srandmember(args ...interface{}) *Reply {
	return c.call(cmdSrandmember, args...)
}

// Srem calls Redis SREM command. 
func (c *Conn) Srem(args ...interface{}) *Reply {
	return c.call(cmdSrem, args...)
}

// Strlen calls Redis STRLEN command. 
func (c *Conn) Strlen(args ...interface{}) *Reply {
	return c.call(cmdStrlen, args...)
}

// Sunion calls Redis SUNION command. 
func (c *Conn) Sunion(args ...interface{}) *Reply {
	return c.call(cmdSunion, args...)
}

// Sunionstore calls Redis SUNIONSTORE command. 
func (c *Conn) Sunionstore(args ...interface{}) *Reply {
	return c.call(cmdSunionstore, args...)
}

// Sync calls Redis SYNC command. 
func (c *Conn) Sync(args ...interface{}) *Reply {
	return c.call(cmdSync, args...)
}

// Time calls Redis TIME command. 
func (c *Conn) Time(args ...interface{}) *Reply {
	return c.call(cmdTime, args...)
}

// Ttl calls Redis TTL command. 
func (c *Conn) Ttl(args ...interface{}) *Reply {
	return c.call(cmdTtl, args...)
}

// Type calls Redis TYPE command. 
func (c *Conn) Type(args ...interface{}) *Reply {
	return c.call(cmdType, args...)
}

// Unwatch calls Redis UNWATCH command. 
func (c *Conn) Unwatch(args ...interface{}) *Reply {
	return c.call(cmdUnwatch, args...)
}

// Watch calls Redis WATCH command. 
func (c *Conn) Watch(args ...interface{}) *Reply {
	return c.call(cmdWatch, args...)
}

// Zadd calls Redis ZADD command. 
func (c *Conn) Zadd(args ...interface{}) *Reply {
	return c.call(cmdZadd, args...)
}

// Zcard calls Redis ZCARD command. 
func (c *Conn) Zcard(args ...interface{}) *Reply {
	return c.call(cmdZcard, args...)
}

// Zcount calls Redis ZCOUNT command. 
func (c *Conn) Zcount(args ...interface{}) *Reply {
	return c.call(cmdZcount, args...)
}

// Zincrby calls Redis ZINCRBY command. 
func (c *Conn) Zincrby(args ...interface{}) *Reply {
	return c.call(cmdZincrby, args...)
}

// Zinterstore calls Redis ZINTERSTORE command. 
func (c *Conn) Zinterstore(args ...interface{}) *Reply {
	return c.call(cmdZinterstore, args...)
}

// Zrange calls Redis ZRANGE command. 
func (c *Conn) Zrange(args ...interface{}) *Reply {
	return c.call(cmdZrange, args...)
}

// Zrangebyscore calls Redis ZRANGEBYSCORE command. 
func (c *Conn) Zrangebyscore(args ...interface{}) *Reply {
	return c.call(cmdZrangebyscore, args...)
}

// Zrank calls Redis ZRANK command. 
func (c *Conn) Zrank(args ...interface{}) *Reply {
	return c.call(cmdZrank, args...)
}

// Zrem calls Redis ZREM command. 
func (c *Conn) Zrem(args ...interface{}) *Reply {
	return c.call(cmdZrem, args...)
}

// Zremrangebyrank calls Redis ZREMRANGEBYRANK command. 
func (c *Conn) Zremrangebyrank(args ...interface{}) *Reply {
	return c.call(cmdZremrangebyrank, args...)
}

// Zremrangebyscore calls Redis ZREMRANGEBYSCORE command. 
func (c *Conn) Zremrangebyscore(args ...interface{}) *Reply {
	return c.call(cmdZremrangebyscore, args...)
}

// Zrevrange calls Redis ZREVRANGE command. 
func (c *Conn) Zrevrange(args ...interface{}) *Reply {
	return c.call(cmdZrevrange, args...)
}

// Zrevrangebyscore calls Redis ZREVRANGEBYSCORE command. 
func (c *Conn) Zrevrangebyscore(args ...interface{}) *Reply {
	return c.call(cmdZrevrangebyscore, args...)
}

// Zrevrank calls Redis ZREVRANK command. 
func (c *Conn) Zrevrank(args ...interface{}) *Reply {
	return c.call(cmdZrevrank, args...)
}

// Zscore calls Redis ZSCORE command. 
func (c *Conn) Zscore(args ...interface{}) *Reply {
	return c.call(cmdZscore, args...)
}

// Zunionstore calls Redis ZUNIONSTORE command. 
func (c *Conn) Zunionstore(args ...interface{}) *Reply {
	return c.call(cmdZunionstore, args...)
}

// AsyncAppend calls Redis APPEND asynchronously. 
func (c *Conn) AsyncAppend(args ...interface{}) Future {
	return c.asyncCall(cmdAppend, args...)
}

// AsyncAsking calls Redis ASKING asynchronously. 
func (c *Conn) AsyncAsking(args ...interface{}) Future {
	return c.asyncCall(cmdAsking, args...)
}

// AsyncAuth calls Redis AUTH asynchronously. 
func (c *Conn) AsyncAuth(args ...interface{}) Future {
	return c.asyncCall(cmdAuth, args...)
}

// AsyncBgrewriteaof calls Redis BGREWRITEAOF asynchronously. 
func (c *Conn) AsyncBgrewriteaof(args ...interface{}) Future {
	return c.asyncCall(cmdBgrewriteaof, args...)
}

// AsyncBgsave calls Redis BGSAVE asynchronously. 
func (c *Conn) AsyncBgsave(args ...interface{}) Future {
	return c.asyncCall(cmdBgsave, args...)
}

// AsyncBitcount calls Redis BITCOUNT asynchronously. 
func (c *Conn) AsyncBitcount(args ...interface{}) Future {
	return c.asyncCall(cmdBitcount, args...)
}

// AsyncBitop calls Redis BITOP asynchronously. 
func (c *Conn) AsyncBitop(args ...interface{}) Future {
	return c.asyncCall(cmdBitop, args...)
}

// AsyncBlpop calls Redis BLPOP asynchronously. 
func (c *Conn) AsyncBlpop(args ...interface{}) Future {
	return c.asyncCall(cmdBlpop, args...)
}

// AsyncBrpop calls Redis BRPOP asynchronously. 
func (c *Conn) AsyncBrpop(args ...interface{}) Future {
	return c.asyncCall(cmdBrpop, args...)
}

// AsyncBrpoplpush calls Redis BRPOPLPUSH asynchronously. 
func (c *Conn) AsyncBrpoplpush(args ...interface{}) Future {
	return c.asyncCall(cmdBrpoplpush, args...)
}

// AsyncClient calls Redis CLIENT asynchronously. 
func (c *Conn) AsyncClient(args ...interface{}) Future {
	return c.asyncCall(cmdClient, args...)
}

// AsyncCluster calls Redis CLUSTER asynchronously. 
func (c *Conn) AsyncCluster(args ...interface{}) Future {
	return c.asyncCall(cmdCluster, args...)
}

// AsyncConfig calls Redis CONFIG asynchronously. 
func (c *Conn) AsyncConfig(args ...interface{}) Future {
	return c.asyncCall(cmdConfig, args...)
}

// AsyncDbsize calls Redis DBSIZE asynchronously. 
func (c *Conn) AsyncDbsize(args ...interface{}) Future {
	return c.asyncCall(cmdDbsize, args...)
}

// AsyncDebug calls Redis DEBUG asynchronously. 
func (c *Conn) AsyncDebug(args ...interface{}) Future {
	return c.asyncCall(cmdDebug, args...)
}

// AsyncDecr calls Redis DECR asynchronously. 
func (c *Conn) AsyncDecr(args ...interface{}) Future {
	return c.asyncCall(cmdDecr, args...)
}

// AsyncDecrby calls Redis DECRBY asynchronously. 
func (c *Conn) AsyncDecrby(args ...interface{}) Future {
	return c.asyncCall(cmdDecrby, args...)
}

// AsyncDel calls Redis DEL asynchronously. 
func (c *Conn) AsyncDel(args ...interface{}) Future {
	return c.asyncCall(cmdDel, args...)
}

// AsyncDiscard calls Redis DISCARD asynchronously. 
func (c *Conn) AsyncDiscard(args ...interface{}) Future {
	return c.asyncCall(cmdDiscard, args...)
}

// AsyncDump calls Redis DUMP asynchronously. 
func (c *Conn) AsyncDump(args ...interface{}) Future {
	return c.asyncCall(cmdDump, args...)
}

// AsyncEcho calls Redis ECHO asynchronously. 
func (c *Conn) AsyncEcho(args ...interface{}) Future {
	return c.asyncCall(cmdEcho, args...)
}

// AsyncEval calls Redis EVAL asynchronously. 
func (c *Conn) AsyncEval(args ...interface{}) Future {
	return c.asyncCall(cmdEval, args...)
}

// AsyncExec calls Redis EXEC asynchronously. 
func (c *Conn) AsyncExec(args ...interface{}) Future {
	return c.asyncCall(cmdExec, args...)
}

// AsyncExists calls Redis EXISTS asynchronously. 
func (c *Conn) AsyncExists(args ...interface{}) Future {
	return c.asyncCall(cmdExists, args...)
}

// AsyncExpire calls Redis EXPIRE asynchronously. 
func (c *Conn) AsyncExpire(args ...interface{}) Future {
	return c.asyncCall(cmdExpire, args...)
}

// AsyncExpireat calls Redis EXPIREAT asynchronously. 
func (c *Conn) AsyncExpireat(args ...interface{}) Future {
	return c.asyncCall(cmdExpireat, args...)
}

// AsyncFlushall calls Redis FLUSHALL asynchronously. 
func (c *Conn) AsyncFlushall(args ...interface{}) Future {
	return c.asyncCall(cmdFlushall, args...)
}

// AsyncFlushdb calls Redis FLUSHDB asynchronously. 
func (c *Conn) AsyncFlushdb(args ...interface{}) Future {
	return c.asyncCall(cmdFlushdb, args...)
}

// AsyncGet calls Redis GET asynchronously. 
func (c *Conn) AsyncGet(args ...interface{}) Future {
	return c.asyncCall(cmdGet, args...)
}

// AsyncGetbit calls Redis GETBIT asynchronously. 
func (c *Conn) AsyncGetbit(args ...interface{}) Future {
	return c.asyncCall(cmdGetbit, args...)
}

// AsyncGetrange calls Redis GETRANGE asynchronously. 
func (c *Conn) AsyncGetrange(args ...interface{}) Future {
	return c.asyncCall(cmdGetrange, args...)
}

// AsyncGetset calls Redis GETSET asynchronously. 
func (c *Conn) AsyncGetset(args ...interface{}) Future {
	return c.asyncCall(cmdGetset, args...)
}

// AsyncHdel calls Redis HDEL asynchronously. 
func (c *Conn) AsyncHdel(args ...interface{}) Future {
	return c.asyncCall(cmdHdel, args...)
}

// AsyncHexists calls Redis HEXISTS asynchronously. 
func (c *Conn) AsyncHexists(args ...interface{}) Future {
	return c.asyncCall(cmdHexists, args...)
}

// AsyncHget calls Redis HGET asynchronously. 
func (c *Conn) AsyncHget(args ...interface{}) Future {
	return c.asyncCall(cmdHget, args...)
}

// AsyncHgetall calls Redis HGETALL asynchronously. 
func (c *Conn) AsyncHgetall(args ...interface{}) Future {
	return c.asyncCall(cmdHgetall, args...)
}

// AsyncHincrby calls Redis HINCRBY asynchronously. 
func (c *Conn) AsyncHincrby(args ...interface{}) Future {
	return c.asyncCall(cmdHincrby, args...)
}

// AsyncHincrbyfloat calls Redis HINCRBYFLOAT asynchronously. 
func (c *Conn) AsyncHincrbyfloat(args ...interface{}) Future {
	return c.asyncCall(cmdHincrbyfloat, args...)
}

// AsyncHkeys calls Redis HKEYS asynchronously. 
func (c *Conn) AsyncHkeys(args ...interface{}) Future {
	return c.asyncCall(cmdHkeys, args...)
}

// AsyncHlen calls Redis HLEN asynchronously. 
func (c *Conn) AsyncHlen(args ...interface{}) Future {
	return c.asyncCall(cmdHlen, args...)
}

// AsyncHmget calls Redis HMGET asynchronously. 
func (c *Conn) AsyncHmget(args ...interface{}) Future {
	return c.asyncCall(cmdHmget, args...)
}

// AsyncHmset calls Redis HMSET asynchronously. 
func (c *Conn) AsyncHmset(args ...interface{}) Future {
	return c.asyncCall(cmdHmset, args...)
}

// AsyncHset calls Redis HSET asynchronously. 
func (c *Conn) AsyncHset(args ...interface{}) Future {
	return c.asyncCall(cmdHset, args...)
}

// AsyncHsetnx calls Redis HSETNX asynchronously. 
func (c *Conn) AsyncHsetnx(args ...interface{}) Future {
	return c.asyncCall(cmdHsetnx, args...)
}

// AsyncHvals calls Redis HVALS asynchronously. 
func (c *Conn) AsyncHvals(args ...interface{}) Future {
	return c.asyncCall(cmdHvals, args...)
}

// AsyncIncr calls Redis INCR asynchronously. 
func (c *Conn) AsyncIncr(args ...interface{}) Future {
	return c.asyncCall(cmdIncr, args...)
}

// AsyncIncrby calls Redis INCRBY asynchronously. 
func (c *Conn) AsyncIncrby(args ...interface{}) Future {
	return c.asyncCall(cmdIncrby, args...)
}

// AsyncIncrbyfloat calls Redis INCRBYFLOAT asynchronously. 
func (c *Conn) AsyncIncrbyfloat(args ...interface{}) Future {
	return c.asyncCall(cmdIncrbyfloat, args...)
}

// AsyncInfo calls Redis INFO asynchronously. 
func (c *Conn) AsyncInfo(args ...interface{}) Future {
	return c.asyncCall(cmdInfo, args...)
}

// AsyncKeys calls Redis KEYS asynchronously. 
func (c *Conn) AsyncKeys(args ...interface{}) Future {
	return c.asyncCall(cmdKeys, args...)
}

// AsyncLastsave calls Redis LASTSAVE asynchronously. 
func (c *Conn) AsyncLastsave(args ...interface{}) Future {
	return c.asyncCall(cmdLastsave, args...)
}

// AsyncLindex calls Redis LINDEX asynchronously. 
func (c *Conn) AsyncLindex(args ...interface{}) Future {
	return c.asyncCall(cmdLindex, args...)
}

// AsyncLinsert calls Redis LINSERT asynchronously. 
func (c *Conn) AsyncLinsert(args ...interface{}) Future {
	return c.asyncCall(cmdLinsert, args...)
}

// AsyncLlen calls Redis LLEN asynchronously. 
func (c *Conn) AsyncLlen(args ...interface{}) Future {
	return c.asyncCall(cmdLlen, args...)
}

// AsyncLpop calls Redis LPOP asynchronously. 
func (c *Conn) AsyncLpop(args ...interface{}) Future {
	return c.asyncCall(cmdLpop, args...)
}

// AsyncLpush calls Redis LPUSH asynchronously. 
func (c *Conn) AsyncLpush(args ...interface{}) Future {
	return c.asyncCall(cmdLpush, args...)
}

// AsyncLpushx calls Redis LPUSHX asynchronously. 
func (c *Conn) AsyncLpushx(args ...interface{}) Future {
	return c.asyncCall(cmdLpushx, args...)
}

// AsyncLrange calls Redis LRANGE asynchronously. 
func (c *Conn) AsyncLrange(args ...interface{}) Future {
	return c.asyncCall(cmdLrange, args...)
}

// AsyncLrem calls Redis LREM asynchronously. 
func (c *Conn) AsyncLrem(args ...interface{}) Future {
	return c.asyncCall(cmdLrem, args...)
}

// AsyncLset calls Redis LSET asynchronously. 
func (c *Conn) AsyncLset(args ...interface{}) Future {
	return c.asyncCall(cmdLset, args...)
}

// AsyncLtrim calls Redis LTRIM asynchronously. 
func (c *Conn) AsyncLtrim(args ...interface{}) Future {
	return c.asyncCall(cmdLtrim, args...)
}

// AsyncMget calls Redis MGET asynchronously. 
func (c *Conn) AsyncMget(args ...interface{}) Future {
	return c.asyncCall(cmdMget, args...)
}

// AsyncMigrate calls Redis MIGRATE asynchronously. 
func (c *Conn) AsyncMigrate(args ...interface{}) Future {
	return c.asyncCall(cmdMigrate, args...)
}

// AsyncMonitor calls Redis MONITOR asynchronously. 
func (c *Conn) AsyncMonitor(args ...interface{}) Future {
	return c.asyncCall(cmdMonitor, args...)
}

// AsyncMove calls Redis MOVE asynchronously. 
func (c *Conn) AsyncMove(args ...interface{}) Future {
	return c.asyncCall(cmdMove, args...)
}

// AsyncMset calls Redis MSET asynchronously. 
func (c *Conn) AsyncMset(args ...interface{}) Future {
	return c.asyncCall(cmdMset, args...)
}

// AsyncMsetnx calls Redis MSETNX asynchronously. 
func (c *Conn) AsyncMsetnx(args ...interface{}) Future {
	return c.asyncCall(cmdMsetnx, args...)
}

// AsyncMulti calls Redis MULTI asynchronously. 
func (c *Conn) AsyncMulti(args ...interface{}) Future {
	return c.asyncCall(cmdMulti, args...)
}

// AsyncObject calls Redis OBJECT asynchronously. 
func (c *Conn) AsyncObject(args ...interface{}) Future {
	return c.asyncCall(cmdObject, args...)
}

// AsyncPersist calls Redis PERSIST asynchronously. 
func (c *Conn) AsyncPersist(args ...interface{}) Future {
	return c.asyncCall(cmdPersist, args...)
}

// AsyncPexpire calls Redis PEXPIRE asynchronously. 
func (c *Conn) AsyncPexpire(args ...interface{}) Future {
	return c.asyncCall(cmdPexpire, args...)
}

// AsyncPexpireat calls Redis PEXPIREAT asynchronously. 
func (c *Conn) AsyncPexpireat(args ...interface{}) Future {
	return c.asyncCall(cmdPexpireat, args...)
}

// AsyncPing calls Redis PING asynchronously. 
func (c *Conn) AsyncPing(args ...interface{}) Future {
	return c.asyncCall(cmdPing, args...)
}

// AsyncPsetex calls Redis PSETEX asynchronously. 
func (c *Conn) AsyncPsetex(args ...interface{}) Future {
	return c.asyncCall(cmdPsetex, args...)
}

// AsyncPttl calls Redis PTTL asynchronously. 
func (c *Conn) AsyncPttl(args ...interface{}) Future {
	return c.asyncCall(cmdPttl, args...)
}

// AsyncPublish calls Redis PUBLISH asynchronously. 
func (c *Conn) AsyncPublish(args ...interface{}) Future {
	return c.asyncCall(cmdPublish, args...)
}

// AsyncRandomkey calls Redis RANDOMKEY asynchronously. 
func (c *Conn) AsyncRandomkey(args ...interface{}) Future {
	return c.asyncCall(cmdRandomkey, args...)
}

// AsyncRename calls Redis RENAME asynchronously. 
func (c *Conn) AsyncRename(args ...interface{}) Future {
	return c.asyncCall(cmdRename, args...)
}

// AsyncRenamenx calls Redis RENAMENX asynchronously. 
func (c *Conn) AsyncRenamenx(args ...interface{}) Future {
	return c.asyncCall(cmdRenamenx, args...)
}

// AsyncReplconf calls Redis REPLCONF asynchronously. 
func (c *Conn) AsyncReplconf(args ...interface{}) Future {
	return c.asyncCall(cmdReplconf, args...)
}

// AsyncRestore calls Redis RESTORE asynchronously. 
func (c *Conn) AsyncRestore(args ...interface{}) Future {
	return c.asyncCall(cmdRestore, args...)
}

// AsyncRpop calls Redis RPOP asynchronously. 
func (c *Conn) AsyncRpop(args ...interface{}) Future {
	return c.asyncCall(cmdRpop, args...)
}

// AsyncRpoplpush calls Redis RPOPLPUSH asynchronously. 
func (c *Conn) AsyncRpoplpush(args ...interface{}) Future {
	return c.asyncCall(cmdRpoplpush, args...)
}

// AsyncRpush calls Redis RPUSH asynchronously. 
func (c *Conn) AsyncRpush(args ...interface{}) Future {
	return c.asyncCall(cmdRpush, args...)
}

// AsyncRpushx calls Redis RPUSHX asynchronously. 
func (c *Conn) AsyncRpushx(args ...interface{}) Future {
	return c.asyncCall(cmdRpushx, args...)
}

// AsyncSadd calls Redis SADD asynchronously. 
func (c *Conn) AsyncSadd(args ...interface{}) Future {
	return c.asyncCall(cmdSadd, args...)
}

// AsyncSave calls Redis SAVE asynchronously. 
func (c *Conn) AsyncSave(args ...interface{}) Future {
	return c.asyncCall(cmdSave, args...)
}

// AsyncScard calls Redis SCARD asynchronously. 
func (c *Conn) AsyncScard(args ...interface{}) Future {
	return c.asyncCall(cmdScard, args...)
}

// AsyncScript calls Redis SCRIPT asynchronously. 
func (c *Conn) AsyncScript(args ...interface{}) Future {
	return c.asyncCall(cmdScript, args...)
}

// AsyncSdiff calls Redis SDIFF asynchronously. 
func (c *Conn) AsyncSdiff(args ...interface{}) Future {
	return c.asyncCall(cmdSdiff, args...)
}

// AsyncSdiffstore calls Redis SDIFFSTORE asynchronously. 
func (c *Conn) AsyncSdiffstore(args ...interface{}) Future {
	return c.asyncCall(cmdSdiffstore, args...)
}

// AsyncSelect calls Redis SELECT asynchronously. 
func (c *Conn) AsyncSelect(args ...interface{}) Future {
	return c.asyncCall(cmdSelect, args...)
}

// AsyncSet calls Redis SET asynchronously. 
func (c *Conn) AsyncSet(args ...interface{}) Future {
	return c.asyncCall(cmdSet, args...)
}

// AsyncSetbit calls Redis SETBIT asynchronously. 
func (c *Conn) AsyncSetbit(args ...interface{}) Future {
	return c.asyncCall(cmdSetbit, args...)
}

// AsyncSetex calls Redis SETEX asynchronously. 
func (c *Conn) AsyncSetex(args ...interface{}) Future {
	return c.asyncCall(cmdSetex, args...)
}

// AsyncSetnx calls Redis SETNX asynchronously. 
func (c *Conn) AsyncSetnx(args ...interface{}) Future {
	return c.asyncCall(cmdSetnx, args...)
}

// AsyncSetrange calls Redis SETRANGE asynchronously. 
func (c *Conn) AsyncSetrange(args ...interface{}) Future {
	return c.asyncCall(cmdSetrange, args...)
}

// AsyncShutdown calls Redis SHUTDOWN asynchronously. 
func (c *Conn) AsyncShutdown(args ...interface{}) Future {
	return c.asyncCall(cmdShutdown, args...)
}

// AsyncSinter calls Redis SINTER asynchronously. 
func (c *Conn) AsyncSinter(args ...interface{}) Future {
	return c.asyncCall(cmdSinter, args...)
}

// AsyncSinterstore calls Redis SINTERSTORE asynchronously. 
func (c *Conn) AsyncSinterstore(args ...interface{}) Future {
	return c.asyncCall(cmdSinterstore, args...)
}

// AsyncSismember calls Redis SISMEMBER asynchronously. 
func (c *Conn) AsyncSismember(args ...interface{}) Future {
	return c.asyncCall(cmdSismember, args...)
}

// AsyncSlaveof calls Redis SLAVEOF asynchronously. 
func (c *Conn) AsyncSlaveof(args ...interface{}) Future {
	return c.asyncCall(cmdSlaveof, args...)
}

// AsyncSmembers calls Redis SMEMBERS asynchronously. 
func (c *Conn) AsyncSmembers(args ...interface{}) Future {
	return c.asyncCall(cmdSmembers, args...)
}

// AsyncSmove calls Redis SMOVE asynchronously. 
func (c *Conn) AsyncSmove(args ...interface{}) Future {
	return c.asyncCall(cmdSmove, args...)
}

// AsyncSort calls Redis SORT asynchronously. 
func (c *Conn) AsyncSort(args ...interface{}) Future {
	return c.asyncCall(cmdSort, args...)
}

// AsyncSpop calls Redis SPOP asynchronously. 
func (c *Conn) AsyncSpop(args ...interface{}) Future {
	return c.asyncCall(cmdSpop, args...)
}

// AsyncSrandmember calls Redis SRANDMEMBER asynchronously. 
func (c *Conn) AsyncSrandmember(args ...interface{}) Future {
	return c.asyncCall(cmdSrandmember, args...)
}

// AsyncSrem calls Redis SREM asynchronously. 
func (c *Conn) AsyncSrem(args ...interface{}) Future {
	return c.asyncCall(cmdSrem, args...)
}

// AsyncStrlen calls Redis STRLEN asynchronously. 
func (c *Conn) AsyncStrlen(args ...interface{}) Future {
	return c.asyncCall(cmdStrlen, args...)
}

// AsyncSunion calls Redis SUNION asynchronously. 
func (c *Conn) AsyncSunion(args ...interface{}) Future {
	return c.asyncCall(cmdSunion, args...)
}

// AsyncSunionstore calls Redis SUNIONSTORE asynchronously. 
func (c *Conn) AsyncSunionstore(args ...interface{}) Future {
	return c.asyncCall(cmdSunionstore, args...)
}

// AsyncSync calls Redis SYNC asynchronously. 
func (c *Conn) AsyncSync(args ...interface{}) Future {
	return c.asyncCall(cmdSync, args...)
}

// AsyncTime calls Redis TIME asynchronously. 
func (c *Conn) AsyncTime(args ...interface{}) Future {
	return c.asyncCall(cmdTime, args...)
}

// AsyncTtl calls Redis TTL asynchronously. 
func (c *Conn) AsyncTtl(args ...interface{}) Future {
	return c.asyncCall(cmdTtl, args...)
}

// AsyncType calls Redis TYPE asynchronously. 
func (c *Conn) AsyncType(args ...interface{}) Future {
	return c.asyncCall(cmdType, args...)
}

// AsyncUnwatch calls Redis UNWATCH asynchronously. 
func (c *Conn) AsyncUnwatch(args ...interface{}) Future {
	return c.asyncCall(cmdUnwatch, args...)
}

// AsyncWatch calls Redis WATCH asynchronously. 
func (c *Conn) AsyncWatch(args ...interface{}) Future {
	return c.asyncCall(cmdWatch, args...)
}

// AsyncZadd calls Redis ZADD asynchronously. 
func (c *Conn) AsyncZadd(args ...interface{}) Future {
	return c.asyncCall(cmdZadd, args...)
}

// AsyncZcard calls Redis ZCARD asynchronously. 
func (c *Conn) AsyncZcard(args ...interface{}) Future {
	return c.asyncCall(cmdZcard, args...)
}

// AsyncZcount calls Redis ZCOUNT asynchronously. 
func (c *Conn) AsyncZcount(args ...interface{}) Future {
	return c.asyncCall(cmdZcount, args...)
}

// AsyncZincrby calls Redis ZINCRBY asynchronously. 
func (c *Conn) AsyncZincrby(args ...interface{}) Future {
	return c.asyncCall(cmdZincrby, args...)
}

// AsyncZinterstore calls Redis ZINTERSTORE asynchronously. 
func (c *Conn) AsyncZinterstore(args ...interface{}) Future {
	return c.asyncCall(cmdZinterstore, args...)
}

// AsyncZrange calls Redis ZRANGE asynchronously. 
func (c *Conn) AsyncZrange(args ...interface{}) Future {
	return c.asyncCall(cmdZrange, args...)
}

// AsyncZrangebyscore calls Redis ZRANGEBYSCORE asynchronously. 
func (c *Conn) AsyncZrangebyscore(args ...interface{}) Future {
	return c.asyncCall(cmdZrangebyscore, args...)
}

// AsyncZrank calls Redis ZRANK asynchronously. 
func (c *Conn) AsyncZrank(args ...interface{}) Future {
	return c.asyncCall(cmdZrank, args...)
}

// AsyncZrem calls Redis ZREM asynchronously. 
func (c *Conn) AsyncZrem(args ...interface{}) Future {
	return c.asyncCall(cmdZrem, args...)
}

// AsyncZremrangebyrank calls Redis ZREMRANGEBYRANK asynchronously. 
func (c *Conn) AsyncZremrangebyrank(args ...interface{}) Future {
	return c.asyncCall(cmdZremrangebyrank, args...)
}

// AsyncZremrangebyscore calls Redis ZREMRANGEBYSCORE asynchronously. 
func (c *Conn) AsyncZremrangebyscore(args ...interface{}) Future {
	return c.asyncCall(cmdZremrangebyscore, args...)
}

// AsyncZrevrange calls Redis ZREVRANGE asynchronously. 
func (c *Conn) AsyncZrevrange(args ...interface{}) Future {
	return c.asyncCall(cmdZrevrange, args...)
}

// AsyncZrevrangebyscore calls Redis ZREVRANGEBYSCORE asynchronously. 
func (c *Conn) AsyncZrevrangebyscore(args ...interface{}) Future {
	return c.asyncCall(cmdZrevrangebyscore, args...)
}

// AsyncZrevrank calls Redis ZREVRANK asynchronously. 
func (c *Conn) AsyncZrevrank(args ...interface{}) Future {
	return c.asyncCall(cmdZrevrank, args...)
}

// AsyncZscore calls Redis ZSCORE asynchronously. 
func (c *Conn) AsyncZscore(args ...interface{}) Future {
	return c.asyncCall(cmdZscore, args...)
}

// AsyncZunionstore calls Redis ZUNIONSTORE asynchronously. 
func (c *Conn) AsyncZunionstore(args ...interface{}) Future {
	return c.asyncCall(cmdZunionstore, args...)
}

// Append queues a Redis APPEND command for later execution. 
func (mc *MultiCall) Append(args ...interface{}) {
	mc.call(cmdAppend, args...)
}

// Asking queues a Redis ASKING command for later execution. 
func (mc *MultiCall) Asking(args ...interface{}) {
	mc.call(cmdAsking, args...)
}

// Auth queues a Redis AUTH command for later execution. 
func (mc *MultiCall) Auth(args ...interface{}) {
	mc.call(cmdAuth, args...)
}

// Bgrewriteaof queues a Redis BGREWRITEAOF command for later execution. 
func (mc *MultiCall) Bgrewriteaof(args ...interface{}) {
	mc.call(cmdBgrewriteaof, args...)
}

// Bgsave queues a Redis BGSAVE command for later execution. 
func (mc *MultiCall) Bgsave(args ...interface{}) {
	mc.call(cmdBgsave, args...)
}

// Bitcount queues a Redis BITCOUNT command for later execution. 
func (mc *MultiCall) Bitcount(args ...interface{}) {
	mc.call(cmdBitcount, args...)
}

// Bitop queues a Redis BITOP command for later execution. 
func (mc *MultiCall) Bitop(args ...interface{}) {
	mc.call(cmdBitop, args...)
}

// Blpop queues a Redis BLPOP command for later execution. 
func (mc *MultiCall) Blpop(args ...interface{}) {
	mc.call(cmdBlpop, args...)
}

// Brpop queues a Redis BRPOP command for later execution. 
func (mc *MultiCall) Brpop(args ...interface{}) {
	mc.call(cmdBrpop, args...)
}

// Brpoplpush queues a Redis BRPOPLPUSH command for later execution. 
func (mc *MultiCall) Brpoplpush(args ...interface{}) {
	mc.call(cmdBrpoplpush, args...)
}

// Client queues a Redis CLIENT command for later execution. 
func (mc *MultiCall) Client(args ...interface{}) {
	mc.call(cmdClient, args...)
}

// Cluster queues a Redis CLUSTER command for later execution. 
func (mc *MultiCall) Cluster(args ...interface{}) {
	mc.call(cmdCluster, args...)
}

// Config queues a Redis CONFIG command for later execution. 
func (mc *MultiCall) Config(args ...interface{}) {
	mc.call(cmdConfig, args...)
}

// Dbsize queues a Redis DBSIZE command for later execution. 
func (mc *MultiCall) Dbsize(args ...interface{}) {
	mc.call(cmdDbsize, args...)
}

// Debug queues a Redis DEBUG command for later execution. 
func (mc *MultiCall) Debug(args ...interface{}) {
	mc.call(cmdDebug, args...)
}

// Decr queues a Redis DECR command for later execution. 
func (mc *MultiCall) Decr(args ...interface{}) {
	mc.call(cmdDecr, args...)
}

// Decrby queues a Redis DECRBY command for later execution. 
func (mc *MultiCall) Decrby(args ...interface{}) {
	mc.call(cmdDecrby, args...)
}

// Del queues a Redis DEL command for later execution. 
func (mc *MultiCall) Del(args ...interface{}) {
	mc.call(cmdDel, args...)
}

// Discard queues a Redis DISCARD command for later execution. 
func (mc *MultiCall) Discard(args ...interface{}) {
	mc.call(cmdDiscard, args...)
}

// Dump queues a Redis DUMP command for later execution. 
func (mc *MultiCall) Dump(args ...interface{}) {
	mc.call(cmdDump, args...)
}

// Echo queues a Redis ECHO command for later execution. 
func (mc *MultiCall) Echo(args ...interface{}) {
	mc.call(cmdEcho, args...)
}

// Eval queues a Redis EVAL command for later execution. 
func (mc *MultiCall) Eval(args ...interface{}) {
	mc.call(cmdEval, args...)
}

// Exec queues a Redis EXEC command for later execution. 
func (mc *MultiCall) Exec(args ...interface{}) {
	mc.call(cmdExec, args...)
}

// Exists queues a Redis EXISTS command for later execution. 
func (mc *MultiCall) Exists(args ...interface{}) {
	mc.call(cmdExists, args...)
}

// Expire queues a Redis EXPIRE command for later execution. 
func (mc *MultiCall) Expire(args ...interface{}) {
	mc.call(cmdExpire, args...)
}

// Expireat queues a Redis EXPIREAT command for later execution. 
func (mc *MultiCall) Expireat(args ...interface{}) {
	mc.call(cmdExpireat, args...)
}

// Flushall queues a Redis FLUSHALL command for later execution. 
func (mc *MultiCall) Flushall(args ...interface{}) {
	mc.call(cmdFlushall, args...)
}

// Flushdb queues a Redis FLUSHDB command for later execution. 
func (mc *MultiCall) Flushdb(args ...interface{}) {
	mc.call(cmdFlushdb, args...)
}

// Get queues a Redis GET command for later execution. 
func (mc *MultiCall) Get(args ...interface{}) {
	mc.call(cmdGet, args...)
}

// Getbit queues a Redis GETBIT command for later execution. 
func (mc *MultiCall) Getbit(args ...interface{}) {
	mc.call(cmdGetbit, args...)
}

// Getrange queues a Redis GETRANGE command for later execution. 
func (mc *MultiCall) Getrange(args ...interface{}) {
	mc.call(cmdGetrange, args...)
}

// Getset queues a Redis GETSET command for later execution. 
func (mc *MultiCall) Getset(args ...interface{}) {
	mc.call(cmdGetset, args...)
}

// Hdel queues a Redis HDEL command for later execution. 
func (mc *MultiCall) Hdel(args ...interface{}) {
	mc.call(cmdHdel, args...)
}

// Hexists queues a Redis HEXISTS command for later execution. 
func (mc *MultiCall) Hexists(args ...interface{}) {
	mc.call(cmdHexists, args...)
}

// Hget queues a Redis HGET command for later execution. 
func (mc *MultiCall) Hget(args ...interface{}) {
	mc.call(cmdHget, args...)
}

// Hgetall queues a Redis HGETALL command for later execution. 
func (mc *MultiCall) Hgetall(args ...interface{}) {
	mc.call(cmdHgetall, args...)
}

// Hincrby queues a Redis HINCRBY command for later execution. 
func (mc *MultiCall) Hincrby(args ...interface{}) {
	mc.call(cmdHincrby, args...)
}

// Hincrbyfloat queues a Redis HINCRBYFLOAT command for later execution. 
func (mc *MultiCall) Hincrbyfloat(args ...interface{}) {
	mc.call(cmdHincrbyfloat, args...)
}

// Hkeys queues a Redis HKEYS command for later execution. 
func (mc *MultiCall) Hkeys(args ...interface{}) {
	mc.call(cmdHkeys, args...)
}

// Hlen queues a Redis HLEN command for later execution. 
func (mc *MultiCall) Hlen(args ...interface{}) {
	mc.call(cmdHlen, args...)
}

// Hmget queues a Redis HMGET command for later execution. 
func (mc *MultiCall) Hmget(args ...interface{}) {
	mc.call(cmdHmget, args...)
}

// Hmset queues a Redis HMSET command for later execution. 
func (mc *MultiCall) Hmset(args ...interface{}) {
	mc.call(cmdHmset, args...)
}

// Hset queues a Redis HSET command for later execution. 
func (mc *MultiCall) Hset(args ...interface{}) {
	mc.call(cmdHset, args...)
}

// Hsetnx queues a Redis HSETNX command for later execution. 
func (mc *MultiCall) Hsetnx(args ...interface{}) {
	mc.call(cmdHsetnx, args...)
}

// Hvals queues a Redis HVALS command for later execution. 
func (mc *MultiCall) Hvals(args ...interface{}) {
	mc.call(cmdHvals, args...)
}

// Incr queues a Redis INCR command for later execution. 
func (mc *MultiCall) Incr(args ...interface{}) {
	mc.call(cmdIncr, args...)
}

// Incrby queues a Redis INCRBY command for later execution. 
func (mc *MultiCall) Incrby(args ...interface{}) {
	mc.call(cmdIncrby, args...)
}

// Incrbyfloat queues a Redis INCRBYFLOAT command for later execution. 
func (mc *MultiCall) Incrbyfloat(args ...interface{}) {
	mc.call(cmdIncrbyfloat, args...)
}

// Info queues a Redis INFO command for later execution. 
func (mc *MultiCall) Info(args ...interface{}) {
	mc.call(cmdInfo, args...)
}

// Keys queues a Redis KEYS command for later execution. 
func (mc *MultiCall) Keys(args ...interface{}) {
	mc.call(cmdKeys, args...)
}

// Lastsave queues a Redis LASTSAVE command for later execution. 
func (mc *MultiCall) Lastsave(args ...interface{}) {
	mc.call(cmdLastsave, args...)
}

// Lindex queues a Redis LINDEX command for later execution. 
func (mc *MultiCall) Lindex(args ...interface{}) {
	mc.call(cmdLindex, args...)
}

// Linsert queues a Redis LINSERT command for later execution. 
func (mc *MultiCall) Linsert(args ...interface{}) {
	mc.call(cmdLinsert, args...)
}

// Llen queues a Redis LLEN command for later execution. 
func (mc *MultiCall) Llen(args ...interface{}) {
	mc.call(cmdLlen, args...)
}

// Lpop queues a Redis LPOP command for later execution. 
func (mc *MultiCall) Lpop(args ...interface{}) {
	mc.call(cmdLpop, args...)
}

// Lpush queues a Redis LPUSH command for later execution. 
func (mc *MultiCall) Lpush(args ...interface{}) {
	mc.call(cmdLpush, args...)
}

// Lpushx queues a Redis LPUSHX command for later execution. 
func (mc *MultiCall) Lpushx(args ...interface{}) {
	mc.call(cmdLpushx, args...)
}

// Lrange queues a Redis LRANGE command for later execution. 
func (mc *MultiCall) Lrange(args ...interface{}) {
	mc.call(cmdLrange, args...)
}

// Lrem queues a Redis LREM command for later execution. 
func (mc *MultiCall) Lrem(args ...interface{}) {
	mc.call(cmdLrem, args...)
}

// Lset queues a Redis LSET command for later execution. 
func (mc *MultiCall) Lset(args ...interface{}) {
	mc.call(cmdLset, args...)
}

// Ltrim queues a Redis LTRIM command for later execution. 
func (mc *MultiCall) Ltrim(args ...interface{}) {
	mc.call(cmdLtrim, args...)
}

// Mget queues a Redis MGET command for later execution. 
func (mc *MultiCall) Mget(args ...interface{}) {
	mc.call(cmdMget, args...)
}

// Migrate queues a Redis MIGRATE command for later execution. 
func (mc *MultiCall) Migrate(args ...interface{}) {
	mc.call(cmdMigrate, args...)
}

// Monitor queues a Redis MONITOR command for later execution. 
func (mc *MultiCall) Monitor(args ...interface{}) {
	mc.call(cmdMonitor, args...)
}

// Move queues a Redis MOVE command for later execution. 
func (mc *MultiCall) Move(args ...interface{}) {
	mc.call(cmdMove, args...)
}

// Mset queues a Redis MSET command for later execution. 
func (mc *MultiCall) Mset(args ...interface{}) {
	mc.call(cmdMset, args...)
}

// Msetnx queues a Redis MSETNX command for later execution. 
func (mc *MultiCall) Msetnx(args ...interface{}) {
	mc.call(cmdMsetnx, args...)
}

// Multi queues a Redis MULTI command for later execution. 
func (mc *MultiCall) Multi(args ...interface{}) {
	mc.call(cmdMulti, args...)
}

// Object queues a Redis OBJECT command for later execution. 
func (mc *MultiCall) Object(args ...interface{}) {
	mc.call(cmdObject, args...)
}

// Persist queues a Redis PERSIST command for later execution. 
func (mc *MultiCall) Persist(args ...interface{}) {
	mc.call(cmdPersist, args...)
}

// Pexpire queues a Redis PEXPIRE command for later execution. 
func (mc *MultiCall) Pexpire(args ...interface{}) {
	mc.call(cmdPexpire, args...)
}

// Pexpireat queues a Redis PEXPIREAT command for later execution. 
func (mc *MultiCall) Pexpireat(args ...interface{}) {
	mc.call(cmdPexpireat, args...)
}

// Ping queues a Redis PING command for later execution. 
func (mc *MultiCall) Ping(args ...interface{}) {
	mc.call(cmdPing, args...)
}

// Psetex queues a Redis PSETEX command for later execution. 
func (mc *MultiCall) Psetex(args ...interface{}) {
	mc.call(cmdPsetex, args...)
}

// Pttl queues a Redis PTTL command for later execution. 
func (mc *MultiCall) Pttl(args ...interface{}) {
	mc.call(cmdPttl, args...)
}

// Publish queues a Redis PUBLISH command for later execution. 
func (mc *MultiCall) Publish(args ...interface{}) {
	mc.call(cmdPublish, args...)
}

// Randomkey queues a Redis RANDOMKEY command for later execution. 
func (mc *MultiCall) Randomkey(args ...interface{}) {
	mc.call(cmdRandomkey, args...)
}

// Rename queues a Redis RENAME command for later execution. 
func (mc *MultiCall) Rename(args ...interface{}) {
	mc.call(cmdRename, args...)
}

// Renamenx queues a Redis RENAMENX command for later execution. 
func (mc *MultiCall) Renamenx(args ...interface{}) {
	mc.call(cmdRenamenx, args...)
}

// Replconf queues a Redis REPLCONF command for later execution. 
func (mc *MultiCall) Replconf(args ...interface{}) {
	mc.call(cmdReplconf, args...)
}

// Restore queues a Redis RESTORE command for later execution. 
func (mc *MultiCall) Restore(args ...interface{}) {
	mc.call(cmdRestore, args...)
}

// Rpop queues a Redis RPOP command for later execution. 
func (mc *MultiCall) Rpop(args ...interface{}) {
	mc.call(cmdRpop, args...)
}

// Rpoplpush queues a Redis RPOPLPUSH command for later execution. 
func (mc *MultiCall) Rpoplpush(args ...interface{}) {
	mc.call(cmdRpoplpush, args...)
}

// Rpush queues a Redis RPUSH command for later execution. 
func (mc *MultiCall) Rpush(args ...interface{}) {
	mc.call(cmdRpush, args...)
}

// Rpushx queues a Redis RPUSHX command for later execution. 
func (mc *MultiCall) Rpushx(args ...interface{}) {
	mc.call(cmdRpushx, args...)
}

// Sadd queues a Redis SADD command for later execution. 
func (mc *MultiCall) Sadd(args ...interface{}) {
	mc.call(cmdSadd, args...)
}

// Save queues a Redis SAVE command for later execution. 
func (mc *MultiCall) Save(args ...interface{}) {
	mc.call(cmdSave, args...)
}

// Scard queues a Redis SCARD command for later execution. 
func (mc *MultiCall) Scard(args ...interface{}) {
	mc.call(cmdScard, args...)
}

// Script queues a Redis SCRIPT command for later execution. 
func (mc *MultiCall) Script(args ...interface{}) {
	mc.call(cmdScript, args...)
}

// Sdiff queues a Redis SDIFF command for later execution. 
func (mc *MultiCall) Sdiff(args ...interface{}) {
	mc.call(cmdSdiff, args...)
}

// Sdiffstore queues a Redis SDIFFSTORE command for later execution. 
func (mc *MultiCall) Sdiffstore(args ...interface{}) {
	mc.call(cmdSdiffstore, args...)
}

// Select queues a Redis SELECT command for later execution. 
func (mc *MultiCall) Select(args ...interface{}) {
	mc.call(cmdSelect, args...)
}

// Set queues a Redis SET command for later execution. 
func (mc *MultiCall) Set(args ...interface{}) {
	mc.call(cmdSet, args...)
}

// Setbit queues a Redis SETBIT command for later execution. 
func (mc *MultiCall) Setbit(args ...interface{}) {
	mc.call(cmdSetbit, args...)
}

// Setex queues a Redis SETEX command for later execution. 
func (mc *MultiCall) Setex(args ...interface{}) {
	mc.call(cmdSetex, args...)
}

// Setnx queues a Redis SETNX command for later execution. 
func (mc *MultiCall) Setnx(args ...interface{}) {
	mc.call(cmdSetnx, args...)
}

// Setrange queues a Redis SETRANGE command for later execution. 
func (mc *MultiCall) Setrange(args ...interface{}) {
	mc.call(cmdSetrange, args...)
}

// Shutdown queues a Redis SHUTDOWN command for later execution. 
func (mc *MultiCall) Shutdown(args ...interface{}) {
	mc.call(cmdShutdown, args...)
}

// Sinter queues a Redis SINTER command for later execution. 
func (mc *MultiCall) Sinter(args ...interface{}) {
	mc.call(cmdSinter, args...)
}

// Sinterstore queues a Redis SINTERSTORE command for later execution. 
func (mc *MultiCall) Sinterstore(args ...interface{}) {
	mc.call(cmdSinterstore, args...)
}

// Sismember queues a Redis SISMEMBER command for later execution. 
func (mc *MultiCall) Sismember(args ...interface{}) {
	mc.call(cmdSismember, args...)
}

// Slaveof queues a Redis SLAVEOF command for later execution. 
func (mc *MultiCall) Slaveof(args ...interface{}) {
	mc.call(cmdSlaveof, args...)
}

// Smembers queues a Redis SMEMBERS command for later execution. 
func (mc *MultiCall) Smembers(args ...interface{}) {
	mc.call(cmdSmembers, args...)
}

// Smove queues a Redis SMOVE command for later execution. 
func (mc *MultiCall) Smove(args ...interface{}) {
	mc.call(cmdSmove, args...)
}

// Sort queues a Redis SORT command for later execution. 
func (mc *MultiCall) Sort(args ...interface{}) {
	mc.call(cmdSort, args...)
}

// Spop queues a Redis SPOP command for later execution. 
func (mc *MultiCall) Spop(args ...interface{}) {
	mc.call(cmdSpop, args...)
}

// Srandmember queues a Redis SRANDMEMBER command for later execution. 
func (mc *MultiCall) Srandmember(args ...interface{}) {
	mc.call(cmdSrandmember, args...)
}

// Srem queues a Redis SREM command for later execution. 
func (mc *MultiCall) Srem(args ...interface{}) {
	mc.call(cmdSrem, args...)
}

// Strlen queues a Redis STRLEN command for later execution. 
func (mc *MultiCall) Strlen(args ...interface{}) {
	mc.call(cmdStrlen, args...)
}

// Sunion queues a Redis SUNION command for later execution. 
func (mc *MultiCall) Sunion(args ...interface{}) {
	mc.call(cmdSunion, args...)
}

// Sunionstore queues a Redis SUNIONSTORE command for later execution. 
func (mc *MultiCall) Sunionstore(args ...interface{}) {
	mc.call(cmdSunionstore, args...)
}

// Sync queues a Redis SYNC command for later execution. 
func (mc *MultiCall) Sync(args ...interface{}) {
	mc.call(cmdSync, args...)
}

// Time queues a Redis TIME command for later execution. 
func (mc *MultiCall) Time(args ...interface{}) {
	mc.call(cmdTime, args...)
}

// Ttl queues a Redis TTL command for later execution. 
func (mc *MultiCall) Ttl(args ...interface{}) {
	mc.call(cmdTtl, args...)
}

// Type queues a Redis TYPE command for later execution. 
func (mc *MultiCall) Type(args ...interface{}) {
	mc.call(cmdType, args...)
}

// Unwatch queues a Redis UNWATCH command for later execution. 
func (mc *MultiCall) Unwatch(args ...interface{}) {
	mc.call(cmdUnwatch, args...)
}

// Watch queues a Redis WATCH command for later execution. 
func (mc *MultiCall) Watch(args ...interface{}) {
	mc.call(cmdWatch, args...)
}

// Zadd queues a Redis ZADD command for later execution. 
func (mc *MultiCall) Zadd(args ...interface{}) {
	mc.call(cmdZadd, args...)
}

// Zcard queues a Redis ZCARD command for later execution. 
func (mc *MultiCall) Zcard(args ...interface{}) {
	mc.call(cmdZcard, args...)
}

// Zcount queues a Redis ZCOUNT command for later execution. 
func (mc *MultiCall) Zcount(args ...interface{}) {
	mc.call(cmdZcount, args...)
}

// Zincrby queues a Redis ZINCRBY command for later execution. 
func (mc *MultiCall) Zincrby(args ...interface{}) {
	mc.call(cmdZincrby, args...)
}

// Zinterstore queues a Redis ZINTERSTORE command for later execution. 
func (mc *MultiCall) Zinterstore(args ...interface{}) {
	mc.call(cmdZinterstore, args...)
}

// Zrange queues a Redis ZRANGE command for later execution. 
func (mc *MultiCall) Zrange(args ...interface{}) {
	mc.call(cmdZrange, args...)
}

// Zrangebyscore queues a Redis ZRANGEBYSCORE command for later execution. 
func (mc *MultiCall) Zrangebyscore(args ...interface{}) {
	mc.call(cmdZrangebyscore, args...)
}

// Zrank queues a Redis ZRANK command for later execution. 
func (mc *MultiCall) Zrank(args ...interface{}) {
	mc.call(cmdZrank, args...)
}

// Zrem queues a Redis ZREM command for later execution. 
func (mc *MultiCall) Zrem(args ...interface{}) {
	mc.call(cmdZrem, args...)
}

// Zremrangebyrank queues a Redis ZREMRANGEBYRANK command for later execution. 
func (mc *MultiCall) Zremrangebyrank(args ...interface{}) {
	mc.call(cmdZremrangebyrank, args...)
}

// Zremrangebyscore queues a Redis ZREMRANGEBYSCORE command for later execution. 
func (mc *MultiCall) Zremrangebyscore(args ...interface{}) {
	mc.call(cmdZremrangebyscore, args...)
}

// Zrevrange queues a Redis ZREVRANGE command for later execution. 
func (mc *MultiCall) Zrevrange(args ...interface{}) {
	mc.call(cmdZrevrange, args...)
}

// Zrevrangebyscore queues a Redis ZREVRANGEBYSCORE command for later execution. 
func (mc *MultiCall) Zrevrangebyscore(args ...interface{}) {
	mc.call(cmdZrevrangebyscore, args...)
}

// Zrevrank queues a Redis ZREVRANK command for later execution. 
func (mc *MultiCall) Zrevrank(args ...interface{}) {
	mc.call(cmdZrevrank, args...)
}

// Zscore queues a Redis ZSCORE command for later execution. 
func (mc *MultiCall) Zscore(args ...interface{}) {
	mc.call(cmdZscore, args...)
}

// Zunionstore queues a Redis ZUNIONSTORE command for later execution. 
func (mc *MultiCall) Zunionstore(args ...interface{}) {
	mc.call(cmdZunionstore, args...)
}
